/* Design rationale for the classroom. Comparisons explain methods; they are not new benchmark runs. */
window.CLASS_DESIGN = {
  zh: {
    encodingIntro: `<h2>同一张文档页，可以怎样编码？</h2><p>先分清两个选择：<strong>输入是提取出的文字，还是整张页面图像？表示是一条向量，还是多条向量？</strong>下面四条路线把这两个问题分开。图中的文字提取可直接读取 PDF 文本层；扫描页通常需要 OCR（光学字符识别）。</p>`,
    encodingCaption: '同一页面的四种表示路线。示意图，不是本项目的四组对照实验；点击可放大。',
    encodingAlt: '文档编码对比：文字词项、文字单向量、页面图像单向量、ColQwen2页面图像多向量，以及各自的匹配方式。',
    encodingMethods: [
      {name:'文字 + BM25',title:'用词项匹配：哪些词共同出现？',body:'把提取的文字分词，记录词频等统计。查询中出现的词与页面词项匹配，BM25 会结合词频、词的稀有程度和长度等打分。它不需要把页面变成神经网络的稠密向量。',example:'“United States”“1960”若被正确提取，关键词检索就可能找到这一页；如果问题写“US”、页面写“United States”，基础词项匹配未必自动理解它们等价。',tradeoff:'容易建立索引和解释词项命中。效果依赖文字提取与词汇匹配；单纯线性文字也可能丢失表头与数值的位置关系。版面解析、查询扩展等可以改善，不能说所有文字方案都忽略版式。'},
      {name:'文字 + 单向量',title:'用语义向量匹配：文字意思接近吗？',body:'把提取出的文字按页或片段切分，用文本编码器把每个检索单元压成一条稠密向量；问题也编码成一条向量，再做点积或余弦比较。稠密表示是由许多数值维度承载信息的表示。',example:'语义训练可使“US”和“United States”更接近。但若 OCR 漏掉 1960，或拆散国家与年份的对应，后续文本向量不能凭空恢复缺失证据。',tradeoff:'通常比逐词匹配更能处理表达差异；每个单元只存一条向量，便于向量搜索。单个向量需要概括整个单元；缩小片段可保留细节，也要维护片段到页面的映射。'},
      {name:'图像 + 单向量',title:'直接看页面，但把整页汇成一条向量',body:'视觉编码器读取页面图像，先汇聚为一个全局表示，再投影到目标维度。问题必须由与它对齐的文本编码器表示，才能计算有意义的相似度；任意两个模型的向量不能直接混用。',example:'页面的图表与位置关系可进入编码器，不依赖外部 OCR 的纯文字输出。但许多局部细节仍需压入同一条全局表示。',tradeoff:'说明“直接看图”与“保留多向量”是两件事。这是一类编码策略，并非说所有视觉检索模型都采用单向量，或单向量一定劣于多向量。'},
      {name:'ColQwen2 · 多向量',title:'直接看页面，让问题的不同部分分别找匹配',body:'页面图像和问题分别编码成多条向量。ColQwen2 为各位置输出 128 维表示；打分时，每个问题位置在页面向量中寻找最相似者，再把这些最佳匹配相加。下一小节会逐格手算。',example:'同一道 REITs 问题的不同部分可以匹配页面上不同的证据信息。每个位置的表示也会受到上下文影响；不能把某条向量直接当成可解释的“1960 向量”。',tradeoff:'保留更细的匹配粒度，页面仍可预先编码和缓存；代价是每页存多条向量，匹配也比一次全局向量点积更复杂。它仍可能漏看细小文字、混淆年份或把主题相近页排高。'}
    ],
    encodingAfter: `<p class="muted">图中把“图像单向量”作为概念路线。真实系统还可组合 OCR、版面解析、文字与图像、稀疏与稠密检索；表中不代表穷尽所有方法。</p><h2>为什么本项目选择 ColQwen2 做检索基线？</h2><div class="grid-three"><article class="card"><h3>数据形态匹配</h3><p>MMDocIR 有图表、表格和幻灯片。直接编码页面，让视觉信息参与匹配，适合检验此类证据检索。</p></article><article class="card"><h3>可固定、可复现</h3><p>使用公开的现成 checkpoint；问题与页面独立编码，页面表示可缓存。本地代码能直接计算分数与候选。</p></article><article class="card"><h3>能看清重排的作用</h3><p>先固定检索器、候选和测试题，再比较原顺序、Base Qwen 与 SFT Qwen，避免同时改检索与重排而无法归因。</p></article></div><p><strong>这是选型理由，不是“本项目已经证明 ColQwen2 最强”。</strong>我们没有在这套数据上重跑 BM25、文字单向量或图像单向量对照。官方文档检索模型的适用性是选择依据，是否在本项目优于其他路线仍需要统一协议的实验。</p><div class="callout"><strong>两种 baseline，分别回答两个问题。</strong><p><strong>ColQwen2 检索基线：</strong>完全不重排，直接按相似度分数交付候选。<strong>Base Qwen 重排基线：</strong>原始指令模型已具备通用能力，但没有做本项目 SFT；它读取相同候选并尝试生成排列。</p></div><h3>既然能编码检索，为什么还要 Qwen 重排？</h3><p>ColQwen2 在打分时匹配独立编码的向量；生成式 Qwen 重排则把<strong>问题与候选图一起输入</strong>，按任务要求生成证据说明和排列。后者可以尝试细读年份、列名和比较关系，但推理开销不同，也不保证一定更好。我们用保存的 Base/SFT 对照来检验它。</p><p class="muted">依据：<a href="https://huggingface.co/vidore/colqwen2-v1.0-hf" target="_blank" rel="noreferrer">ColQwen2 官方模型卡</a>、<a href="https://arxiv.org/abs/2407.01449" target="_blank" rel="noreferrer">ColPali 文档视觉检索论文</a>、<a href="https://arxiv.org/abs/2004.12832" target="_blank" rel="noreferrer">ColBERT 后期交互论文</a>、<a href="https://arxiv.org/abs/2004.04906" target="_blank" rel="noreferrer">DPR 单向量检索论文</a>。词项检索参考 <a href="https://nlp.stanford.edu/IR-book/html/htmledition/okapi-bm25-a-non-binary-model-1.html" target="_blank" rel="noreferrer">BM25 作者教材</a>。本地候选与计算见本节源码。</p>`,
    teacherIntro: `<h2>先看真实图片生成分析，再精炼监督文本</h2><div id="supervision-boundary" class="callout"><strong>制作监督答案与学生 SFT 是两个阶段。</strong><p><strong>教师准备监督：</strong>问题 + 单张真实页面图片 + 正负标签 → 看图生成逐页分析 → 纯文字精炼。</p><p><strong>学生训练：</strong>问题 + 全部真实候选图片 → Qwen 学习生成精炼证据说明与完整排列。精炼文本是监督目标，原始候选图片仍作为输入；正负标签不放进学生 prompt。</p></div><p>数据集告诉我们“哪些页相关”，通常<strong>没有提供符合本任务格式的逐页证据说明</strong>。如果希望 SFT 同时学习“指出证据 + 输出完整排列”，就需要补出前半部分示范。这里借助 Gemini 制作教材；部署时 Qwen 自己生成，不需要每题再调用 Gemini。</p><p>逐页分析把每次任务限定为“这张图对这个问题提供什么证据”，便于检查负例为什么不够用；精炼则把重复笔记变成简短、带候选编号的统一说明。逐页看图负责收集证据，精炼负责整理监督文本；这两步发生在准备训练样本时。</p>`,
    teacherCaption:'两条流程：教师看真实单页图制作监督；学生继续读取真实候选图做 SFT。图中编号对应保存的训练顺序，图 3 为正例；点击可放大。',
    teacherAlt:'教师读取真实单页图生成分析后做文字精炼；学生继续输入问题和全部真实候选图片，以精炼证据和排列作为监督目标。',
    teacherSteps:[
      {name:'① 逐页分析',title:'一次只看一张图：把证据和当前编号绑定',input:'问题 + 单张真实候选图 + 数据集提供的该页相关性标签。其他候选图不在这次请求中。',output:'每页一段简短笔记；提示要求不超过 40 个英文词。相关页说明可见证据，负例说明为什么不足以回答。',example:'图 1：目录提到 REITs，但没有美国起始年。\n图 3：时间轴写 United States (1960)，直接支持所问年份。\n图 2、4、5：各有页面内容，但没有直接给出美国起始年。',reason:'把任务拆小，显式覆盖每页，减少只谈某张显眼页面的机会，也方便后续逐图核查。标签是参考，不能代替看图。'},
      {name:'② 文本精炼',title:'只整理笔记：删重复、保留证据和编号',input:'问题 + 带候选编号的全部笔记 + 代码已算好的 preferred_page_order。只有这次精炼请求不重复传图；逐页分析已经读取过真实图片，学生训练仍输入真实候选图。',output:'一段统一的证据摘要；提示要求不超过 100 个英文词。教师输出说明文本，目标排列仍由代码控制。',example:'图 3 的美国 1960 年时间轴直接回答问题；图 1 为目录，图 2 为印度 REITs 与市场数量材料，图 4、5 为发行与上市规定，均没有该起始年。',reason:'避免把五段重复说明直接拼成长目标；让学生模仿简短一致的证据格式。它能整理已有文字，但无法仅靠这些笔记重新核验原图中漏读的数字。'},
      {name:'③ 组装 SFT 目标',title:'代码把说明与正确排列写到不同字段',input:'精炼后的公开证据摘要 + 根据 gold 与当前编号映射构造的目标排列。',output:'assistant completion；学生的 prompt 只包含问题、指令和候选图，不包含 gold 或检索分数。',example:'<think>图 3 含美国 1960 年起始证据；其余页不含该年份……</think>\n<answer>[3, 2, 1, 5, 4]</answer>',reason:'教师负责证据文字，程序负责排序结构。这样没有把“让 Gemini 猜标签”当作监督来源；SFT 仍会学习说明和格式，错误说明也可能被学进去。'}
    ],
    teacherAfter:`<h3>这一步为什么值得做，又有哪些代价？</h3><table><thead><tr><th>设计</th><th>希望解决什么</th><th>必须核查什么</th></tr></thead><tbody><tr><td>每页一份笔记</td><td>覆盖正例与易混淆负例，并绑定编号</td><td>图中是否真有该年份、列名、人群与单位</td></tr><tr><td>再做文字精炼</td><td>去掉重复，让训练目标更短、更一致</td><td>是否丢失关键限定，或把原来的错误写得更肯定</td></tr><tr><td>代码生成排列</td><td>正确页前置，保证所有编号恰好一次</td><td>打乱后图片、标签与排列是否仍对应</td></tr></tbody></table><p>一条成功、未命中缓存且无重试的 K 页样本需要 <strong>K+1 次教师请求</strong>：K=5 时是 5 次逐页加 1 次精炼。多一阶段会增加标注时间和费用；相应代码提供缓存、重试与费用上限。这个成本发生在准备训练示范时。</p><p><strong>还可以只用排列做 SFT，或一次把全部图交给教师。</strong>本项目采用“说明 + 排列”的目标，需要相应的证据示范；要判断这些额外说明或精炼是否提高新题表现，应保持训练预算与评估协议一致，分别比较这些变体。当前结果没有隔离出这一步的因果贡献。</p><p>这是一种通过输出示范传递任务行为的<strong>监督蒸馏</strong>，不复制 Gemini 的参数。<code>&lt;think&gt;</code> 在本项目中是<strong>公开证据摘要</strong>的容器，不是对模型内部思维的直接观测。教师可能读错图；学生排序正确也不能证明说明事实正确。</p><p class="muted">依据：<a href="assets/sources/src__docreranker__annotation.py.txt" target="_blank">已保存的教师标注源码</a>、<a href="assets/sources/src__docreranker__prompts.py.txt" target="_blank">学生输入输出协议</a>。上方例句均为人工教学简写；原始保存答案可在下方展开。</p>`,
  },
  en: {
    encodingIntro:`<h2>How can we encode the same document page?</h2><p>Separate two choices: <strong>do we input extracted text or the full page image, and do we represent each unit with one vector or many?</strong> The four routes below distinguish these choices. Text extraction can read a PDF text layer directly; scanned pages usually require OCR, or optical character recognition.</p>`,
    encodingCaption:'Four representation routes for one page. This is an explanatory diagram, not four experiments run in our project. Click to enlarge.',
    encodingAlt:'Document encoding comparison: text terms, a single text vector, a single page-image vector, and ColQwen2 multiple page-image vectors, with their matching rules.',
    encodingMethods:[
      {name:'Text + BM25',title:'Term matching: which words occur in both?',body:'Tokenize extracted text and collect statistics such as term frequencies. BM25 scores matching query terms using frequency, rarity and length normalization. It does not require a neural dense embedding of the page.',example:'If “United States” and “1960” are extracted correctly, lexical retrieval may find this page. Basic term matching need not automatically connect the query’s “US” to the page’s “United States.”',tradeoff:'Supports indexing and interpretable term matches. It depends on extraction and vocabulary overlap; a plain linear text stream may lose header–value relationships. Layout parsing and query expansion can help, so text-based methods do not all discard layout.'},
      {name:'Text + one vector',title:'Semantic matching: is the text similar in meaning?',body:'Split extracted text into pages or chunks and encode each retrieval unit as one dense vector. Encode the question as another vector and compare using a dot product or cosine similarity. A dense representation carries information across many numerical dimensions.',example:'Semantic training can bring “US” and “United States” closer together. But if OCR omits 1960 or separates a country from its year, a later text embedding cannot simply recover that missing evidence.',tradeoff:'Can handle wording differences better than basic lexical matching. One vector per unit supports vector search, but must summarize the unit. Smaller chunks preserve granularity while requiring chunk-to-page mapping.'},
      {name:'Image + one vector',title:'Read the image, then summarize the page in one vector',body:'A visual encoder reads the page image aggregates its features into one global representation, then projects it to the target dimension. The question needs a text encoder aligned with that visual representation; vectors from arbitrary unrelated models are not interchangeable.',example:'Charts and spatial relationships can enter the encoder without an external OCR text output. Many local details must still be represented within one global vector.',tradeoff:'Image input and multiple-vector output are separate choices. This is a family of encoding strategies, not a claim that every visual retriever uses one vector or that one vector must perform worse.'},
      {name:'ColQwen2 · many vectors',title:'Let different question positions find separate matches',body:'Encode the page image and question independently as multiple vectors. ColQwen2 projects each position to 128 dimensions. When scoring, each question position finds its strongest page-vector match; sum these maxima. We calculate this next.',example:'Different parts of the REITs question can match different evidence on the page. Position representations are contextualized; a vector is not an explicitly interpretable “1960 vector.”',tradeoff:'Retains a finer matching granularity while allowing page encoding and caching in advance. Multiple vectors require storage and more matching work than one global dot product. Small text, dates or merely topical pages can still cause errors.'}
    ],
    encodingAfter:`<p class="muted">The image-single-vector route is conceptual. Real systems can also combine OCR, layout parsing, text, images, sparse retrieval and dense retrieval; these four routes are not exhaustive.</p><h2>Why choose ColQwen2 as our retrieval baseline?</h2><div class="grid-three"><article class="card"><h3>Fits the page content</h3><p>MMDocIR includes charts, tables and slides. Encoding page images lets visual information participate in evidence matching.</p></article><article class="card"><h3>Fixed and reproducible</h3><p>A public checkpoint is available. Questions and pages are encoded separately, so page representations can be cached and scored by our local code.</p></article><article class="card"><h3>Makes reranking measurable</h3><p>Fix the retriever, candidates and test questions, then compare retrieval order, Base Qwen and SFT Qwen. Changing both stages would complicate attribution.</p></article></div><p><strong>These are selection reasons, not evidence that ColQwen2 is best in this project.</strong> We have not rerun BM25, text-single-vector or image-single-vector baselines on this setup. Suitability for visual documents informs the choice; superiority here requires experiments under a shared protocol.</p><div class="callout"><strong>Two baselines answer two different questions.</strong><p><strong>ColQwen2 retrieval baseline:</strong> no reranker; return candidates in similarity order. <strong>Base Qwen reranking baseline:</strong> the original instruction model has general capabilities but no project-specific SFT; it reads the same candidates and attempts a permutation.</p></div><h3>If retrieval already encodes the pages, why rerank with Qwen?</h3><p>ColQwen2 matches independently encoded vectors when scoring. The generative Qwen reranker takes <strong>the question and candidate images together</strong>, then generates an evidence summary and ordering. It can attempt closer comparisons of dates, columns and relationships, at a different inference cost. Improvement is not guaranteed; our saved Base/SFT comparison tests it.</p><p class="muted">Sources: <a href="https://huggingface.co/vidore/colqwen2-v1.0-hf" target="_blank" rel="noreferrer">the official ColQwen2 model card</a>, <a href="https://arxiv.org/abs/2407.01449" target="_blank" rel="noreferrer">the ColPali paper on visual document retrieval</a> and <a href="https://arxiv.org/abs/2004.12832" target="_blank" rel="noreferrer">the ColBERT late-interaction paper</a>. <a href="https://arxiv.org/abs/2004.04906" target="_blank" rel="noreferrer">DPR single-vector retrieval</a> provides the text-retrieval reference. See also the <a href="https://nlp.stanford.edu/IR-book/html/htmledition/okapi-bm25-a-non-binary-model-1.html" target="_blank" rel="noreferrer">BM25 authors’ textbook</a>. Local scoring code is available below.</p>`,
    teacherIntro:`<h2>Read real images first, then refine the supervision text</h2><div id="supervision-boundary" class="callout"><strong>Preparing supervision and training the SFT student are separate stages.</strong><p><strong>Teacher preparation:</strong> question + one real page image + its relevance label → image-grounded per-page analysis → text-only refinement.</p><p><strong>Student training:</strong> question + all real candidate images → Qwen learns to generate refined evidence and a complete order. Refined text supplies the target; the original candidate images remain inputs. Gold labels stay out of the student prompt.</p></div><p>The dataset identifies relevant pages but usually <strong>does not supply page-evidence explanations in our target format</strong>. To train SFT on both evidence and a complete ordering, we need demonstrations of the explanation as well. Gemini helps prepare those examples; at deployment Qwen generates its own output without calling Gemini for every query.</p><p>Per-page analysis narrows each request to “what evidence does this image provide for this question?” It also makes negative pages inspectable. Refinement turns repetitive notes into one concise explanation with candidate indices. Per-page image analysis collects evidence; refinement organizes the supervision text. Both happen when preparing training examples.</p>`,
    teacherCaption:'Two connected stages: the teacher analyzes real pages to prepare targets; the student still reads real candidate images during SFT. Indices follow the saved training order, with image 3 relevant. Click to enlarge.',
    teacherAlt:'The teacher reads real pages before text refinement. Student SFT still takes the question and all real candidate images, with refined evidence and a permutation as its target.',
    teacherSteps:[
      {name:'① Per-page notes',title:'One image per request: bind visible evidence to its index',input:'The question, one real candidate image and its dataset relevance label. Other candidate images are not included in this request.',output:'One short note per page; the prompt requests at most 40 English words. Describe visible support on relevant pages and why negative pages are insufficient.',example:'Image 1: an agenda mentions REITs, but gives no US start year.\nImage 3: the timeline says United States (1960), directly supporting the requested year.\nImages 2, 4, 5: other material without that US start year.',reason:'A smaller task explicitly covers every page and makes page-by-page auditing easier. It reduces the opportunity to discuss only a conspicuous page. A reference label does not replace reading the image.'},
      {name:'② Text refinement',title:'Organize the notes: remove repetition and retain indices',input:'The question, all indexed notes and preferred_page_order already computed by code. Only this refinement request omits the images. Per-page analysis has already read them; student training still receives real candidate images.',output:'One consolidated evidence summary; the prompt requests at most 100 English words. The teacher writes explanation text; code still controls the target permutation.',example:'Image 3 directly answers the question with the US 1960 timeline. Image 1 is an agenda, image 2 covers REITs in India and market counts, and images 4–5 concern issuing and listing rules; none gives that start year.',reason:'Avoid concatenating five repetitive notes into a long target. Give the student a concise, consistent evidence format. Refinement organizes text; it cannot recheck an omitted image value from the notes alone.'},
      {name:'③ Assemble the target',title:'Code writes the explanation and correct order separately',input:'The refined public evidence summary and the target order built from gold plus the current candidate-index mapping.',output:'An assistant completion. The student prompt contains the question, instructions and candidate images, without gold labels or retrieval scores.',example:'<think>Image 3 gives the US 1960 start-year evidence; the remaining pages do not…</think>\n<answer>[3, 2, 1, 5, 4]</answer>',reason:'The teacher supplies evidence text; code supplies ranking structure. Supervision does not depend on Gemini guessing the relevance labels. SFT also imitates explanation and format, so factual errors in demonstrations may be learned.'}
    ],
    teacherAfter:`<h3>What do these stages buy, and what do they cost?</h3><table><thead><tr><th>Design</th><th>Intended benefit</th><th>What to check</th></tr></thead><tbody><tr><td>One note per page</td><td>Cover positive and confusable negative pages with explicit indices</td><td>Whether the stated year, column, population and unit are visible</td></tr><tr><td>Text refinement</td><td>Remove repetition and shorten and standardize the training target</td><td>Lost qualifications or an earlier error restated confidently</td></tr><tr><td>Code-built permutation</td><td>Place gold first and use every index exactly once</td><td>Image, label and ranking alignment after shuffling</td></tr></tbody></table><p>A successful uncached example with K pages and no retries uses <strong>K+1 teacher requests</strong>: with K=5, five page requests plus one refinement. The extra stage costs annotation time and money; the code provides caching, retries and cost limits. This cost occurs when preparing training demonstrations.</p><p><strong>Ranking-only SFT or a single teacher call with all images are also possible.</strong> Our explanation-plus-order target needs evidence demonstrations. To test whether those explanations or refinement improve new-question performance, compare these variants under matched training budgets and evaluation protocols. Current results do not isolate this stage’s causal contribution.</p><p>This is <strong>supervised distillation</strong> through output examples, not copying Gemini’s weights. In this project, <code>&lt;think&gt;</code> contains a <strong>public evidence summary</strong>, not direct observation of internal reasoning. Teachers can misread images, and a correct ranking does not establish factual explanation accuracy.</p><p class="muted">Sources: <a href="assets/sources/src__docreranker__annotation.py.txt" target="_blank">the saved teacher annotation code</a> and <a href="assets/sources/src__docreranker__prompts.py.txt" target="_blank">the student output protocol</a>. Examples above are manual teaching abbreviations. The exact saved target is available below.</p>`,
  }
};
