/* Core teaching remains visible. Detailed source records and engineering stay expandable. */
window.CLASS_FOUNDATIONS = {
  zh: {
    ragIntro: `<p class="chapter-intro">假设你有一份报告，想问“美国 REITs 从哪一年开始？”模型可能学过相关知识，但我们希望它根据<strong>这份资料中的证据</strong>回答。<strong>RAG（Retrieval-Augmented Generation，检索增强生成）</strong>就是把“先找资料，再依据资料回答”接成一个系统。</p>
      <div class="grid-three"> <article class="card"><div class="card-number">R</div><h3>Retrieval · 检索</h3><p>从已有资料中找出可能有用的页面或片段。</p></article><article class="card"><div class="card-number">A</div><h3>Augmented · 增强</h3><p>把找到的资料加到问题旁边，作为模型回答时的上下文。</p></article><article class="card"><div class="card-number">G</div><h3>Generation · 生成</h3><p>模型结合问题与资料，写出回答，并可附上来源。</p></article></div>
      <h2>先把完整流程走一遍</h2><p>下面仍用同一道 REITs 问题。点击步骤，观察每一步拿到什么、交出什么；这是流程回放，不会调用模型。</p>`,
    ragAfter: `<h2>为什么中间还要“重排”？</h2><p>检索先从较多页面里选出少量候选，追求快速缩小范围。候选中可能有同一主题但不同年份的表格，或只出现关键词的目录。重排序模型再细看这些候选，把直接支持回答的页面放到前面。</p>
      <div class="grid-two"><article class="card"><h3>本项目改进：证据页的顺序</h3><p>ColQwen2 先检索，Qwen 再重排。我们用 SFT 训练重排模型，并学习 GRPO 的基础。实验衡量“相关页排得多靠前”。</p></article><article class="card"><h3>下游使用：根据证据回答</h3><p>回答模型可以读取靠前的证据，写出“1960 年”。这一回答步骤用于说明完整 RAG；本次实验没有测量最终回答正确率。</p></article></div>
      <h2>RAG、提示词与微调，不是同一件事</h2><table><thead><tr><th>做法</th><th>主要改变什么</th><th>本项目中的例子</th></tr></thead><tbody><tr><td>提示词</td><td>这次给模型的任务要求</td><td>要求返回全部候选编号的排列</td></tr><tr><td>RAG</td><td>这次回答可参考的外部资料</td><td>先找证据页，再交给回答模型</td></tr><tr><td>SFT 微调</td><td>通过训练改变模型参数</td><td>教 Qwen 输出简短证据与完整排列</td></tr></tbody></table>
      <p>新增一份文档到检索索引，不等于模型参数已经学会它；RAG 可以不经过本项目 SFT 就运行。SFT 则让模型更适应我们规定的重排任务。两者可以配合使用。</p>
      <p class="muted">来源：<a href="https://arxiv.org/abs/2005.11401" target="_blank" rel="noreferrer">RAG 原始论文</a>。本图的重排环节是面向本项目加入的系统设计。</p>`,
    dataIntro: `<h2>我们用什么数据练习这个任务？</h2><p><strong>MMDocIR</strong> 是面向多模态文档检索的数据集与评估基准。“多模态”在这里指页面中除了文字，还有图表、表格和版式；“检索”关注找到相关页面，而不是只预测一个文本答案。</p><p>训练来源覆盖科学论文、幻灯片和文档问答等数据。本课选用其中 <strong>SlideVQA</strong> 的真实例子：一题、一组页面图像，以及数据集已经提供的相关页标注。当前下载源包括 ArxivQA、DUDE、MP-DocVQA、SciQAG、SlideVQA、TAT-DQA 和 Wiki-ss；它们不是本次训练各用了同样多样本。</p>`,
    dataAfter: `<h2>读懂三个字段，再往下走</h2><table><thead><tr><th>字段</th><th>意思</th><th>这一题</th></tr></thead><tbody><tr><td><code>query</code></td><td>要找证据的问题</td><td>美国 REITs 的开始年份</td></tr><tr><td><code>positive_passages</code></td><td>数据集标为相关的页面，常叫 gold</td><td>数据页号 4</td></tr><tr><td><code>negative_passages</code></td><td>源文件提供的负例页面</td><td>数据页号 1，目录页</td></tr></tbody></table>
      <p><strong>Gold 是参考标签，不是检索器的判断。</strong>它让我们能构造训练目标，也能给模型输出打分。原记录指向的是页面，不是把“1960”直接当作这个重排任务的类别标签。真实数据也可能有漏标，因此案例仍需要核查页面证据。</p>
      <h2>模型练习与最后考试，要用不同的题</h2><div class="grid-three"><article class="card"><h3>训练：7,200 题</h3><p>本次实际生成并用于 SFT 的示范，用来更新参数。不是整个 MMDocIR 的规模。</p></article><article class="card"><h3>验证：160 题</h3><p>从独立验证池固定抽取，用来比较检查点和决定保留哪一步。</p></article><article class="card"><h3>测试：1,658 题</h3><p>来自官方评估数据，313 篇文档；在最后统一比较 Base 与 SFT。</p></article></div>
      <p>同一文档里的问题通常相关，所以先按文档分组划分，再检查训练与测试的文档名、问句是否重叠。如果训练时已经看过期末题，成绩就不能说明对新问题的能力。</p>
      <p class="muted">来源：<a href="https://huggingface.co/datasets/MMDocIR/MMDocIR_Train_Dataset" target="_blank" rel="noreferrer">MMDocIR 训练数据</a>与<a href="https://huggingface.co/datasets/MMDocIR/MMDocIR_Evaluation_Dataset/blob/main/README.md" target="_blank" rel="noreferrer">官方评估数据说明</a>。本次使用量以保存的项目记录为准。</p>`,
    retrievalIntro: `<h2>ColQwen2 是什么模型？</h2><p>它是一个<strong>视觉文档检索模型</strong>：输入问题文本或页面图像，输出用于相似度匹配的数值表示，而不是聊天答案。所用版本基于 Qwen2-VL-2B-Instruct，为输入中的多个位置产生各 <strong>128 维</strong>的向量，并对每个向量做长度归一化。</p><p>可以把向量理解为一串描述内容特征的数字。问题有多组向量，页面也有多组向量，所以它能比较问题的不同部分与页面的局部信息。它与后面会生成排序文字的 <strong>Qwen2.5-VL-7B</strong> 是两个不同角色的模型。</p>
      <table><thead><tr><th>什么时候</th><th>做什么</th><th>保留什么</th></tr></thead><tbody><tr><td>预先建索引</td><td>ColQwen2 读取每张页面图像，编码成多向量</td><td>页面 ID、图片路径与向量缓存</td></tr><tr><td>新问题到来</td><td>编码问题，与页面向量匹配，计算每页分数</td><td>分数从高到低的候选页面</td></tr></tbody></table>
      <p>预先缓存页面表示后，提问时不用重新编码每张页面。页面中的文字、表格与版式一起作为图像输入；本流程不要求先把它们全部转写成纯文字。</p>
      <p class="muted">来源：<a href="https://huggingface.co/vidore/colqwen2-v1.0-hf" target="_blank" rel="noreferrer">ColQwen2 官方模型卡</a>与<a href="https://huggingface.co/docs/transformers/model_doc/colqwen2" target="_blank" rel="noreferrer">Transformers 官方说明</a>。</p>`,
    scoreIntro: `<h2>每一页的分数怎么算？</h2><p>先从一次比较开始：两个向量做<strong>点积</strong>，就是把对应数字相乘再相加。例如 <code>[0.6, 0.8] · [1, 0] = 0.6</code>。两个向量长度都为 1 时，点积等于余弦相似度。</p><p>设问题有 m 个向量 q，某张页面有 n 个向量 d。先计算 m×n 次点积；<strong>每一行取最大值，再把各行最大值相加</strong>。这叫 MaxSim，也是一种“后期交互”：先独立编码，再在打分时让两边的局部表示匹配。</p>
      <div class="formula">S(Q, D) = Σᵢ maxⱼ (qᵢ · dⱼ)</div><p>i 遍历问题位置，j 遍历页面位置。每个问题位置可以选择页面上最匹配的位置；不要求不同问题位置选到不同页面位置。下面用 3×3 的人工相似度矩阵手算，真实模型的位置数量远大于 3。</p>`,
    scoreAfter: `<p><strong>这只是相关性分数，不是正确概率。</strong>多个最大值相加后可以大于 1，而且受问题长度等影响。本题真实分数 18.6391 不表示“正确率 18.64%”；我们主要用分数比较同一个问题下哪些页面更靠前。</p><p>本地实现先移除 attention mask 标记的 padding，再做下面这步。<code>Q</code> 的形状为 m×128，<code>D</code> 为 n×128；转置后相乘得到 m×n 的相似度矩阵。</p>`,
    kIntro: `<h2>为什么取 5 页？为什么不全给模型？</h2><p><strong>5 是本次实验设定的 top-K 候选预算，是可调参数，不是数据集规定的正确页数，也不是 ColQwen2 自动给出的类别数。</strong>当前代码默认 <code>--top-k 5</code>。我们没有做不同 K 的对照来证明 5 最优。</p><table><thead><tr><th>候选较少</th><th>候选较多</th></tr></thead><tbody><tr><td>重排处理的图片少，通常开销更低；但更容易在第一步漏掉证据。</td><td>有机会覆盖更多相关页；但模型要读更多图片、处理更长输入，也可能受更多干扰。</td></tr></tbody></table><p>固定一份检索顺序时，扩大 K 不会减少已召回的相关页；但最后的重排成绩不保证随 K 一直提高。合理做法是在验证集比较不同 K 的效果、延迟和显存，再确定测试设置。</p>`,
    kAfter: `<h2>回到本题：我们到底选了哪 5 页？</h2><p>源数据为这份文档提供 7 张可用页面，数据页号是 <code>[1, 4, 5, 15, 16, 20, 21]</code>。ColQwen2 从这些页面中选择分数最高的 5 张；这不代表原始幻灯片总共只有 7 页。</p><p>绿色标记来自数据集的相关页标签，分数来自 ColQwen2。这里原检索已经把证据页 4 排第一，所以此例用于说明数据流，不用来证明训练提高了成绩。之后会看真实的改善和退步案例。</p><div class="callout"><strong>K 与 gold 的数量独立。</strong><p>本题 K=5，但只有 1 个标注相关页。如果可用页面只有 3 张，就使用 3 张；如果某题有多个 gold，评估分母仍保留全部 gold，重排找不回候选之外的页面。</p></div>`,
    labelsAfter: `<h2>四样东西，各自由谁提供？</h2><table><thead><tr><th>东西</th><th>来源</th><th>用途</th></tr></thead><tbody><tr><td>相关页 label / gold</td><td>数据集的 positive_passages</td><td>构造监督与离线评分</td></tr><tr><td>检索 score</td><td>ColQwen2 的 MaxSim</td><td>选候选，并在同类页中提供顺序约定</td></tr><tr><td>证据摘要</td><td>Gemini 逐页笔记，再精炼</td><td>给学生模型一份可模仿的证据示范</td></tr><tr><td>目标排列</td><td>代码根据 gold 和编号映射生成</td><td>教学生输出完整排序</td></tr></tbody></table>
      <p>代码先把相关页放在前面，再按检索分数排列相关页内部与负例内部。这个顺序是训练目标的构造规则；数据集并没有给每两个负例都标一个唯一正确先后。</p><div class="callout"><strong>困难负例（hard negative）是什么？</strong><p>是<strong>检索分数高、却被数据集标为不相关</strong>的页面。它不是“随便找一张错误图片”，也不等同于原记录的 <code>negative_passages</code> 字段。本题目录页谈 REITs，印度发展页也主题相近，却没有美国起始年份。把这类容易混淆的候选放进训练，目的是让模型区分“谈论同一主题”和“直接提供所问证据”。</p></div><h2>一条完整监督样本怎么制成？</h2><ol><li><strong>准备候选：</strong>训练时保证相关页在候选里，并加入分数高的负例，让模型学会区分容易混淆的页面。测试时不能补相关页。</li><li><strong>打乱并重编号：</strong>图片、页面 ID、正确编号和目标排列同步改变，避免把“第一个候选总是对的”当捷径。</li><li><strong>教师写证据：</strong>Gemini 每次看一页，结合问题与该页标签写简短笔记；然后精炼所有笔记。K 张图通常对应 K 次逐页请求和 1 次精炼。</li><li><strong>组装目标并检查：</strong>代码写入证据摘要与完整编号数组；校验结构，再抽查年份、单位和表格列是否读对。</li></ol><p><strong>学生做题时只看问题、指令和候选图片。</strong>Gold 标签与检索分数不放进学生提示；它们用于制作教材和评分。教师能看到标签，但也可能误读图表，不能把老师写得肯定当作事实验证。</p>`,
    resultsIntro: `<h2>公平的比较要固定什么？</h2><p>纯检索直接使用 ColQwen2 顺序；Base 让原始 Qwen 根据同样的图片与提示重排；SFT 使用同一基础模型加训练后的适配器。三者的候选集合保持不变，测试阶段不插入 gold。</p><p>格式规则要求一段非空证据说明与一个包含所有候选编号的完整排列。比如 5 张图只输出 <code>[3]</code>，即使选中的页有用，也没有完成本项目的完整排序协议。无效输出回退原检索顺序，并保留这道题继续评分。</p>`,
    resultsAfter: `<h2>Macro Recall 为什么不等于“答对题数的比例”？</h2><p>先按每题的全部相关页计算 Recall，再对题目等权平均。人工例子：第 1 题首位命中 1/1 个相关页，第 2 题首位命中 1/4 个相关页。<strong>Macro Recall@1 = (1 + 0.25)/2 = 0.625</strong>；将命中数与相关页数直接合并则是 Micro Recall@1 = 2/5 = 0.4；两题第一名都相关，Hit@1 则为 1。这里图表报告 Macro Recall。</p><h2>把“做得更好”拆成三个问题</h2><table><thead><tr><th>问题</th><th>证据</th><th>不能替代什么</th></tr></thead><tbody><tr><td>输出能被程序使用吗？</td><td>格式成功率与回退率</td><td>不等于看对了图表</td></tr><tr><td>相关页更靠前了吗？</td><td>完整测试的 Recall、MRR、nDCG</td><td>不等于每道题都进步</td></tr><tr><td>解释事实正确吗？</td><td>逐页核对人群、年份、列名、单位</td><td>不能由格式或排名自动证明</td></tr></tbody></table><p>本次 SFT 相对 Base 的 Recall@1 提高约 3.09 个百分点，包含格式学习的作用。看平均提升之后，还要打开下面的真实案例，读原始输出，并检查改善或退步背后的原因。</p>`
  },
  en: {
    ragIntro: `<p class="chapter-intro">Suppose you have a report and ask, “In what year did REITs start in the US?” A model may know something about this, but we want an answer grounded in <strong>this document’s evidence</strong>. <strong>RAG (Retrieval-Augmented Generation)</strong> connects finding evidence with answering from it.</p>
      <div class="grid-three"><article class="card"><div class="card-number">R</div><h3>Retrieval</h3><p>Find potentially useful pages or passages in the available material.</p></article><article class="card"><div class="card-number">A</div><h3>Augmented</h3><p>Add the retrieved evidence to the question as the model’s answering context.</p></article><article class="card"><div class="card-number">G</div><h3>Generation</h3><p>Use the question and evidence to write an answer, optionally with a source citation.</p></article></div>
      <h2>Walk through the whole system first</h2><p>We keep the same REITs question. Click a stage to see what goes in and what comes out. This is an explanation of the pipeline, not a live model call.</p>`,
    ragAfter: `<h2>Why add reranking in the middle?</h2><p>Retrieval quickly narrows many pages to a shortlist. Candidates may include a similar table from the wrong year or an agenda containing only the right keywords. A reranker examines the shortlist more carefully and brings direct evidence to the front.</p>
      <div class="grid-two"><article class="card"><h3>Our component: evidence order</h3><p>ColQwen2 retrieves; Qwen reranks. We train the reranker with SFT and introduce GRPO. The experiment measures how high relevant pages appear.</p></article><article class="card"><h3>Downstream use: an answer</h3><p>An answering model can use the leading evidence to write “1960.” This explains the complete RAG system; final-answer accuracy is not measured in this experiment.</p></article></div>
      <h2>RAG, prompting and fine-tuning do different jobs</h2><table><thead><tr><th>Method</th><th>What it changes</th><th>In this project</th></tr></thead><tbody><tr><td>Prompting</td><td>The instructions for this request</td><td>Ask for a complete candidate permutation</td></tr><tr><td>RAG</td><td>The external evidence available for this answer</td><td>Find pages and pass them to an answering model</td></tr><tr><td>SFT</td><td>Model parameters through training</td><td>Teach Qwen concise evidence and a complete order</td></tr></tbody></table><p>Adding a document to an index does not teach its contents to the model’s parameters. RAG can run without this project’s SFT. SFT adapts the model to our reranking task; the two can be used together.</p><p class="muted">Source: <a href="https://arxiv.org/abs/2005.11401" target="_blank" rel="noreferrer">the original RAG paper</a>. The diagram adds the reranking component used in this project.</p>`,
    dataIntro: `<h2>What data do we use to learn this task?</h2><p><strong>MMDocIR</strong> provides data and benchmarks for multimodal document retrieval. Here, “multimodal” means page text together with tables, charts and layout. “Retrieval” means finding relevant pages rather than merely predicting a text answer.</p><p>The training sources cover scientific papers, slides and document question answering. We use a real <strong>SlideVQA</strong> example: one question, page images and existing relevance annotations. The downloaded sources include ArxivQA, DUDE, MP-DocVQA, SciQAG, SlideVQA, TAT-DQA and Wiki-ss; this does not mean our run samples equal numbers from each.</p>`,
    dataAfter: `<h2>Understand three fields before moving on</h2><table><thead><tr><th>Field</th><th>Meaning</th><th>This example</th></tr></thead><tbody><tr><td><code>query</code></td><td>The question needing evidence</td><td>When US REITs began</td></tr><tr><td><code>positive_passages</code></td><td>Pages labeled relevant, also called gold</td><td>Dataset page ID 4</td></tr><tr><td><code>negative_passages</code></td><td>A negative example supplied by the source</td><td>Dataset page ID 1, an agenda</td></tr></tbody></table><p><strong>Gold is a reference annotation, not the retriever’s judgment.</strong> It supports training targets and evaluation. The annotation points to a page; “1960” is not the class label for this reranking task. Real annotations can omit relevant evidence, so page-level inspection still matters.</p>
      <h2>Practice questions and the final exam must be separate</h2><div class="grid-three"><article class="card"><h3>Training: 7,200 questions</h3><p>The examples actually annotated and used for this SFT run, not the total size of MMDocIR.</p></article><article class="card"><h3>Validation: 160 questions</h3><p>A fixed sample from a separate validation pool, used to compare and choose checkpoints.</p></article><article class="card"><h3>Testing: 1,658 questions</h3><p>From the official evaluation release, spanning 313 documents; used for the final Base/SFT comparison.</p></article></div><p>Questions from the same document are often related. Split by document first, then check document names and questions for train–test overlap. A model that has already seen the exam questions does not provide an independent test of new-question performance.</p><p class="muted">Sources: <a href="https://huggingface.co/datasets/MMDocIR/MMDocIR_Train_Dataset" target="_blank" rel="noreferrer">MMDocIR training data</a> and <a href="https://huggingface.co/datasets/MMDocIR/MMDocIR_Evaluation_Dataset/blob/main/README.md" target="_blank" rel="noreferrer">the evaluation dataset card</a>. Run-specific counts come from the saved project records.</p>`,
    retrievalIntro: `<h2>What is ColQwen2?</h2><p>It is a <strong>visual document retrieval model</strong>. It maps a question or page image to numerical representations for matching, rather than writing a chat answer. Our version uses a Qwen2-VL-2B-Instruct backbone and projects multiple input positions to <strong>128-dimensional vectors</strong>, normalizing each vector’s length.</p><p>A vector is a list of numbers representing content features. Both the question and page have multiple vectors, allowing different parts of the question to match local page information. This is a different model and role from the <strong>Qwen2.5-VL-7B</strong> reranker that later generates a textual ordering.</p>
      <table><thead><tr><th>When</th><th>Operation</th><th>What is retained</th></tr></thead><tbody><tr><td>Indexing beforehand</td><td>Encode each page image as multiple vectors</td><td>Page identity, image path and cached vectors</td></tr><tr><td>A question arrives</td><td>Encode the question and score it against page vectors</td><td>Candidate pages ordered by score</td></tr></tbody></table><p>Caching page representations avoids encoding every page again for each question. Text, tables and layout enter as page images; this pipeline does not require first transcribing everything into plain text.</p><p class="muted">Sources: <a href="https://huggingface.co/vidore/colqwen2-v1.0-hf" target="_blank" rel="noreferrer">the official ColQwen2 model card</a> and <a href="https://huggingface.co/docs/transformers/model_doc/colqwen2" target="_blank" rel="noreferrer">Transformers documentation</a>.</p>`,
    scoreIntro: `<h2>How does a page get its score?</h2><p>Start with one comparison. A <strong>dot product</strong> multiplies corresponding vector entries and sums the products: <code>[0.6, 0.8] · [1, 0] = 0.6</code>. For unit-length vectors, the dot product equals cosine similarity.</p><p>Let the question contain m vectors q and a page contain n vectors d. Compute the m×n dot products. <strong>Take the maximum in each row, then sum those maxima.</strong> This is MaxSim, a form of late interaction: encode the inputs separately, then match their local representations when scoring.</p><div class="formula">S(Q, D) = Σᵢ maxⱼ (qᵢ · dⱼ)</div><p>i runs over question positions; j runs over page positions. Each question position chooses its best match on the page. Different question positions may choose the same page position. The following 3×3 matrix is a teaching example; the real model uses many more positions.</p>`,
    scoreAfter: `<p><strong>This is a relevance score, not a probability.</strong> The sum can exceed 1 and depends on factors such as question length. The real score 18.6391 does not mean “18.64% correct.” We primarily compare pages for the same question.</p><p>The local encoder removes positions marked as padding by the attention mask before scoring. In the code below, <code>Q</code> has shape m×128 and <code>D</code> has shape n×128. Multiplying by the transpose produces an m×n similarity matrix.</p>`,
    kIntro: `<h2>Why five pages? Why not send everything?</h2><p><strong>Five is this project’s top-K setting.</strong> It is adjustable, not the number of correct pages in the dataset and not a number of classes produced by ColQwen2. The current code defaults to <code>--top-k 5</code>. We have not run a K ablation establishing five as optimal.</p><table><thead><tr><th>Fewer candidates</th><th>More candidates</th></tr></thead><tbody><tr><td>Fewer images for the reranker, usually lowering cost; more risk of missing evidence at retrieval.</td><td>More opportunity to include relevant pages, but more images, longer inputs and potentially more distractions.</td></tr></tbody></table><p>For a fixed retrieval ordering, increasing K cannot reduce the relevant pages already retrieved. Final reranking quality need not improve monotonically. Compare quality, latency and memory on validation data before fixing K for testing.</p>`,
    kAfter: `<h2>Back to our question: which five pages were selected?</h2><p>The source supplies seven available pages for this document, with dataset page IDs <code>[1, 4, 5, 15, 16, 20, 21]</code>. ColQwen2 picks the five highest scores among them. This does not mean the original slide deck contains only seven pages.</p><p>The green relevance markers come from dataset annotations; the scores come from ColQwen2. Retrieval already places evidence page 4 first here. We use this example to follow the data flow, then examine real improvements and regressions later.</p><div class="callout"><strong>K and the number of gold pages are independent.</strong><p>Here K=5 but there is one labeled relevant page. If only three pages are available, use three. If a query has multiple gold pages, all stay in the evaluation denominator, including any missed by retrieval.</p></div>`,
    labelsAfter: `<h2>Four different objects, four distinct roles</h2><table><thead><tr><th>Object</th><th>Source</th><th>Purpose</th></tr></thead><tbody><tr><td>Relevance labels / gold</td><td>Dataset positive_passages</td><td>Supervision construction and offline scoring</td></tr><tr><td>Retrieval score</td><td>ColQwen2 MaxSim</td><td>Select candidates and order pages within each group</td></tr><tr><td>Evidence summary</td><td>Gemini’s per-page notes, then refinement</td><td>An evidence demonstration for the student to imitate</td></tr><tr><td>Target ordering</td><td>Code combining gold with the index mapping</td><td>Teach a complete permutation</td></tr></tbody></table><p>Code places relevant pages first, ordering both relevant and negative groups internally by retrieval score. This is a target-construction rule; the dataset does not label a unique correct ordering for every pair of negative pages.</p>
      <div class="callout"><strong>What is a hard negative?</strong><p>A page with a <strong>high retrieval score but a negative dataset label</strong>. It is not an arbitrary wrong image, nor is it the same thing as the source <code>negative_passages</code> field. Here, an agenda mentions REITs and another page covers REITs in India, but neither gives the US start year. Training with confusable candidates aims to teach the difference between sharing a topic and supplying the requested evidence.</p></div><h2>How is one complete supervised example made?</h2><ol><li><strong>Prepare candidates:</strong> training construction retains the relevant pages and adds high-scoring negatives so the model learns to distinguish confusable pages. Testing must not insert gold pages.</li><li><strong>Shuffle and renumber:</strong> move image paths, page IDs, positive indices and target ranks together, reducing the shortcut of assuming the first candidate is always correct.</li><li><strong>Ask the teacher for evidence:</strong> Gemini sees one page at a time with its question and relevance label, then refines the collected notes. K images usually require K page requests and one refinement.</li><li><strong>Assemble and check:</strong> code writes the summary and complete index array; validate the structure and inspect dates, units and table columns.</li></ol><p><strong>The student sees only the question, instructions and candidate images.</strong> Gold and retrieval scores are used to build examples and score outputs, not included in the student prompt. The teacher sees labels but can still misread charts; confidence is not factual verification.</p>`,
    resultsIntro: `<h2>What makes the comparison fair?</h2><p>Retrieval alone uses ColQwen2’s order. Base asks the original Qwen to rerank the same images with the same prompt. SFT uses that base model plus the trained adapter. Candidate sets are fixed, and testing inserts no gold pages.</p><p>The protocol requires one nonempty evidence summary and one complete candidate permutation. With five images, returning only <code>[3]</code> fails this task’s output contract even if image 3 is useful. Invalid outputs fall back to retrieval order, and the query stays in the evaluation.</p>`,
    resultsAfter: `<h2>Why is Macro Recall different from the fraction of questions answered correctly?</h2><p>Compute Recall against each query’s full gold set, then average queries equally. Toy example: rank one finds 1/1 relevant pages for query 1, and 1/4 for query 2. <strong>Macro Recall@1 = (1 + 0.25)/2 = 0.625</strong>. Pooling hits and gold counts gives Micro Recall@1 = 2/5 = 0.4. Both first-ranked pages are relevant, so Hit@1 is 1. Our chart reports Macro Recall.</p><h2>Separate three meanings of “better”</h2><table><thead><tr><th>Question</th><th>Evidence</th><th>What it cannot establish</th></tr></thead><tbody><tr><td>Can the program use the output?</td><td>Format success and fallback rates</td><td>Whether the chart was read correctly</td></tr><tr><td>Are relevant pages nearer the top?</td><td>Full-test Recall, MRR and nDCG</td><td>Improvement on every query</td></tr><tr><td>Is the explanation factual?</td><td>Checking population, year, columns and units on the page</td><td>Not established by format or ranking alone</td></tr></tbody></table><p>SFT improves Recall@1 over Base by about 3.09 percentage points in this run, including the effect of learning the output format. After the aggregate result, open the real cases below and inspect why individual queries improve or regress.</p>`
  }
};
